### ISSUE TITLE
Lab 1 - The tests are located in `test.spec.js` instead of `test.js`.

### ISSUE THREAD

**Issue by MartenBE** [HOGENT-MLOps/mlops-labs#22]
https://github.com/HOGENT-MLOps/mlops-labs/blob/720a1c33d6252e9660abd7b7e19149007ecc1b50/assignment/01-docker.md?plain=1#L128C8-L128C8

**Comment by thomasaelbrecht** [comment]
This is fixed in <https://github.com/HOGENT-MLOps/mlops-labs/blob/04ae7c443fd66129777b383074d610321e6e2590/assignment/01-docker.md?plain=1#L130>
