### ISSUE TITLE
curl check fails on HTTPS

### ISSUE THREAD

**Issue by MartenBE** [HOGENT-MLOps/mlops-labs#42]
https://github.com/HOGENT-MLOps/mlops-labs/blob/76cb66e62ad0be4c37a79277d23bb71a47e43643/scripts/role-deps.sh#L148

Add `--insecure` to prevent the followoing issue:

![image](https://github.com/HOGENT-MLOps/mlops-labs/assets/1958780/ba0043f9-cab6-4ebc-bbc3-c63497d94566)

**Comment by thomasaelbrecht** [comment]
Volgend jaar gaat dit script er uit en werken we zonder Ansible in de dockerlab omgeving.
