### ISSUE TITLE
Lab 4 - echoserver is incompatible with Apple Silicon

### ISSUE THREAD

**Issue by thomasaelbrecht** [HOGENT-MLOps/mlops-labs#45]
See <https://github.com/HOGENT-MLOps/mlops-2324-DeSmetElias/blob/main/report/reports/report-labo4.md>, maybe fabricate something with nginx or something like that?

**Comment by MartenBE** [comment]
I don't have an M1 processor, so I can't reproduce

**Comment by thomasaelbrecht** [comment]
Sorry, this was already fixed! I used the image referenced in [this issue](https://github.com/kubernetes/minikube/issues/11107).

For example:

https://github.com/HOGENT-MLOps/mlops-labs/blob/acd5aa7177679ff68b39640ca16d28303da2f21e/kubernetes/4.2/echo-all.yml#L18
